# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68e19b42a3508ce4b303ca1c62a173ca5326c86ee9bfd15efcd08681233930292a417dc6f2cfce3fa22962cfca49cd4ec0eefe793e6294e9d6886d486539ce79

test:
  secret_key_base: 805bcc6da021417cd2cbf25f8703db01dbc3ed68a10a99875510df4360f65e07480e540e2cfcbc1f046dadf8505a759170c0e96ca4255ed552482064405b9f79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
